version: '3.8'

services:
  spring-boot-test:
    container_name: spring-boot-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
