# project info
project:
  name: Test Server - Spring Boot

# common - Settings
server:
  address: 0.0.0.0
  port: 4000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://125.133.75.11:3307/test-maria-db
    username: root
    password: gjxoran0!
---
project:
  version: Local
