name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Setup SSH for GitHub
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Copy files via SSH and deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@125.133.75.11 << 'EOF'
            cd /spring-boot-test  # Update this path as needed
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:work-ethanhuh/spring-boot-test.git
            fi
            git pull origin main
            ./gradlew clean build
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          EOF
